apiVersion: v1
kind: ConfigMap
metadata:
  name: animal-predict-config
  namespace: animal-app-namespace
data:
  NODE_ENV: "production"
  NEXTAUTH_URL: "http://velocitramphendarius.store/"
  PREDICTION_SERVICE_URL: "http://animal-predict-app-service:80"