apiVersion: v1
kind: ConfigMap
metadata:
  name: animal-predict-config
  namespace: animal-app-namespace
data:
  NODE_ENV: "production"
  NEXTAUTH_URL: "__NEXTAUTH_URL__"
  PREDICTION_SERVICE_URL: "__PREDICTION_SERVICE_URL__"