apiVersion: v1
kind: Secret
metadata:
  name: animal-predict-secret
  namespace: animal-predict
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ""  # Set via GitHub secrets
  GOOGLE_CLIENT_SECRET: ""  # Set via GitHub secrets
  NEXTAUTH_SECRET: ""  # Set via GitHub secrets