apiVersion: v1
kind: Service
metadata:
  name: animal-predict-service
  namespace: animal-predict
  labels:
    app: animal-predict
spec:
  type: LoadBalancer
  selector:
    app: animal-predict
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None